const configuration = {
    // Цена отпечатка
    printingCost5to9: "90",
    printingCost10to49: "40",
    printingCost50to99: "30",
    printingCost100to199: "25",
    printingCost200to299: "20",
    printingCost300to499: "18",
    printingCost500to: "16",
    // Цена сгиба (фальцовки)
    foldingCost: "2",
    // Цена сгиба (фальцовки)
    roundingCost: "2",
    // Цена перфорации
    perforationCost: "2",
    // Цена фигурной резки плоттером
    curlyPlotterCuttingCost: "60",
    // Цена фигурной резки лазером
    curlyLaserCuttingCost: "60",
    // Цена точки персонализации
    personalizationCost: "1.5",
    // Цена клеевой точки
    gluePointCost: "4",
    // Форматы бумаги
    formats: [
        {
            value: "1",
            formatType: "A3+",
            formatWidth: "330",
            formatHeight: "483",
            layoutOnA3Plus: "1",
            minEdition: "5",
        },
        {
            value: "2",
            formatType: "A3",
            formatWidth: "297",
            formatHeight: "420",
            layoutOnA3Plus: "1",
            minEdition: "5",
        },
        {
            value: "3",
            formatType: "A4",
            formatWidth: "210",
            formatHeight: "297",
            layoutOnA3Plus: "2",
            minEdition: "10",
        },
        {
            value: "4",
            formatType: "A5",
            formatWidth: "148",
            formatHeight: "210",
            layoutOnA3Plus: "4",
            minEdition: "20",
        },
        {
            value: "5",
            formatType: "A6",
            formatWidth: "105",
            formatHeight: "148",
            layoutOnA3Plus: "8",
            minEdition: "40",
        },
        {
            value: "6",
            formatType: "A7",
            formatWidth: "74",
            formatHeight: "105",
            layoutOnA3Plus: "16",
            minEdition: "80",
        },
        {
            value: "7",
            formatType: "Евроформат",
            formatWidth: "98",
            formatHeight: "210",
            layoutOnA3Plus: "6",
            minEdition: "30",
        },
        {
            value: "8",
            formatType: "Визитка (станд.)",
            formatWidth: "90",
            formatHeight: "50",
            layoutOnA3Plus: "24",
            minEdition: "100",
        },
        {
            value: "9",
            formatType: "Визитка (евро)",
            formatWidth: "85",
            formatHeight: "55",
            layoutOnA3Plus: "25",
            minEdition: "100",
        },
        {
            value: "10",
            formatType: "Календарь",
            formatWidth: "70",
            formatHeight: "100",
            layoutOnA3Plus: "18",
            minEdition: "100",
        },
        {
            value: "11",
            formatType: "Открытка",
            formatWidth: "210",
            formatHeight: "210",
            layoutOnA3Plus: "2",
            minEdition: "20",
        },
        {
            value: "12",
            formatType: "Кубарик",
            formatWidth: "90",
            formatHeight: "90",
            layoutOnA3Plus: "12",
            minEdition: "100",
        },
        {
            value: "13",
            formatType: "Кубарик",
            formatWidth: "100",
            formatHeight: "100",
            layoutOnA3Plus: "12",
            minEdition: "100",
        },
    ],
    // Типы бумаги
    paperTypes: [
        {
            value: "1",
            paperType: "Для цифровой печати",
            paperDensity: "120",
            paperListPrice: "11",
        },
        {
            value: "2",
            paperType: "Для цифровой печати",
            paperDensity: "160",
            paperListPrice: "14",
        },
        {
            value: "3",
            paperType: "Для цифровой печати",
            paperDensity: "200",
            paperListPrice: "18",
        },
        {
            value: "4",
            paperType: "Для цифровой печати",
            paperDensity: "250",
            paperListPrice: "24",
        },
        {
            value: "5",
            paperType: "Для цифровой печати",
            paperDensity: "300",
            paperListPrice: "28",
        },
        {
            value: "6",
            paperType: "Для цифровой печати",
            paperDensity: "350",
            paperListPrice: "40",
        },
        {
            value: "7",
            paperType: "Самоклеящаяся бумага",
            paperDensity: "180",
            paperListPrice: "26",
        },
        {
            value: "8",
            paperType: "Дизайнерская бумага",
            paperDensity: "120-150",
            paperListPrice: "55",
        },
        {
            value: "9",
            paperType: "Дизайнерская бумага",
            paperDensity: "230-250",
            paperListPrice: "80",
        },
        {
            value: "10",
            paperType: "Дизайнерская бумага",
            paperDensity: "270-300",
            paperListPrice: "170",
        },
        {
            value: "11",
            paperType: "Touche Cover белая",
            paperDensity: "300",
            paperListPrice: "220",
        },
        {
            value: "12",
            paperType: 'С фактурой "ЛЁН"',
            paperDensity: "120-150",
            paperListPrice: "60",
        },
        {
            value: "13",
            paperType: 'С фактурой "ЛЁН"',
            paperDensity: "270-300",
            paperListPrice: "90",
        },
    ],
    // Типы ламинации
    laminationTypes: [
        {
            value: "0",
            laminationType: "Нет",
            laminationSize: "",
            laminationPrices: {},
        },
        {
            value: "1",
            laminationType: "Матовая",
            laminationSize: "40",
            laminationPrices: {
                1: "70",
                2: "70",
                3: "35",
                4: "20",
                5: "10",
                6: "5",
                7: "15",
                8: "3",
                9: "3",
                10: "4",
                11: "35",
                12: "6",
                13: "6",
            },
        },
        {
            value: "2",
            laminationType: "Матовая",
            laminationSize: "125",
            laminationPrices: {
                1: "105",
                2: "105",
                3: "55",
                4: "30",
                5: "15",
                6: "10",
                7: "20",
                8: "5",
                9: "5",
                10: "6",
                11: "55",
                12: "10",
                13: "10",
            },
        },
        {
            value: "3",
            laminationType: "Глянцевая",
            laminationSize: "40",
            laminationPrices: {
                1: "70",
                2: "70",
                3: "35",
                4: "20",
                5: "10",
                6: "5",
                7: "15",
                8: "3",
                9: "3",
                10: "4",
                11: "35",
                12: "6",
                13: "6",
            },
        },
        {
            value: "4",
            laminationType: "Глянцевая",
            laminationSize: "125",
            laminationPrices: {
                1: "105",
                2: "105",
                3: "55",
                4: "30",
                5: "15",
                6: "10",
                7: "20",
                8: "5",
                9: "5",
                10: "6",
                11: "55",
                12: "10",
                13: "10",
            },
        },
        {
            value: "5",
            laminationType: "Soft Touch",
            laminationSize: "",
            laminationPrices: {
                1: "90",
                2: "90",
                3: "45",
                4: "25",
                5: "15",
                6: "10",
                7: "20",
                8: "4",
                9: "4",
                10: "5",
                11: "45",
                12: "8",
                13: "8",
            },
        },
    ],
}
